title = "Wikty"
# hostname (and path) to the root, e.g. http://example.com/blog/
# if deploy on github pages, maybe is http://your-username.github.io/repo-name
baseURL = "http://wikty.github.io/blog/"
languageCode = "zh-cn"
theme = "ananke"

# frontmatter format: "toml", "yaml", "json"
MetaDataFormat = "yaml"
# auto-detect Chinese/Japanese/Korean Languages in the content. (.Summary and .WordCount can work properly in CJKLanguage)
hasCJKLanguage = true
DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Life is a playground or nothing."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/wikty"
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/home_page.jpg"
  comment = true
  share = true
  # cn or us
  country = "cn"
  disqusShortname = "your-disqus-shortname"
  # duoshuo has been shutdown
  duoshuoShortname = "your-duoshuo-shortname"

[blackfriday]
  extensions = ["fencedCode", "strikethrough", "footnotes"]
